version: "3.9"
services:
  api:
    build: .
    container_name: tienanh-pdf-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
      - model-cache:/app/model-image
    # Uncomment the following lines if you need GPU (CUDA) in the container
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

volumes:
  model-cache:

